export const events = [
  {
    image: "/images/event1.png",
    title: "React Summit 2026",
    slug: "react-summit-2026",
    location: "Amsterdam, NL",
    date: "2026-06-19",
    time: "9:00 AM - 5:30 PM",
  },
  {
    image: "/images/event2.png",
    title: "JSConf Asia 2026",
    slug: "jsconf-asia-2026",
    location: "Singapore",
    date: "2026-11-12",
    time: "9:00 AM - 6:00 PM",
  },
  {
    image: "/images/event3.png",
    title: "Google I/O Extended Meetup",
    slug: "google-io-extended-meetup",
    location: "San Francisco, CA",
    date: "2026-05-20",
    time: "6:00 PM - 9:00 PM",
  },
  {
    image: "/images/event4.png",
    title: "Global Hackathon Week",
    slug: "global-hackathon-week",
    location: "Online",
    date: "2026-03-09",
    time: "10:00 AM - 10:00 PM",
  },
  {
    image: "/images/event5.png",
    title: "PyCon US 2026",
    slug: "pycon-us-2026",
    location: "Pittsburgh, PA",
    date: "2026-04-22",
    time: "9:00 AM - 5:00 PM",
  },
  {
    image: "/images/event6.png",
    title: "Cloud Native Meetup",
    slug: "cloud-native-meetup",
    location: "London, UK",
    date: "2026-02-28",
    time: "6:30 PM - 9:00 PM",
  },
];
